apiVersion: v1
kind: Namespace
metadata:
  name: traefik-ingress
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik-ingress
  namespace: traefik-ingress
spec:
  interval: 24h
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-ingress
  namespace: traefik-ingress
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: ">=21.0.0 <22.0.0"
      sourceRef:
        kind: HelmRepository
        name: traefik-ingress
        namespace: traefik-ingress
      interval: 12h
  values:
    deployment:
      enabled: true
    ingressClass:
      enabled: true
      isDefaultClass: true
    ports:
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true
    additionalArguments:
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--providers.kubernetesingress.namespaces=traefik-ingress,nginx"