apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - traefik-ingress.yaml

configMapGenerator:
  - name: traefik-values
    namespace: traefik-ingress
    files:
      - traefik-values.yaml